# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ab81f0b0d7c3418427ee15109452085f0b4fb59c1f586b5ed79f00e76aa8016847da32488a04dfe86c44e4397695c11c8a16e21e6c5fa70cbb5031314e14440

test:
  secret_key_base: 903cc13f1ba16140eccd3c736bc9c37a4a1fe531f8972af80ba44abbda641b9c67c074cffe2cc1aed893e2e8549e9cfc349572424347d9ed065db8a37021064d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
